### ISSUE TITLE
Is rling faster than 'sort -u' ?

### ISSUE THREAD

**Issue by fa1rid** [Cynosureprime/rling#9]
Hey guys, thanks for the nice project.

Is 'rling -s -d' options faster than 'sort -u' ?
Did anyone make benchmarks regarding that? I will do my own tests very soon however.

Also in your example:
`find /path/to/names -type f -print0 | xargs -0 gzcat | rling stdin stdout | gzip -9 > all-names.txt.gz`
I'm just curious to ask you why did you use gzip knowing that lzma2 compression is far superior?

Regards.

**Comment by Waffle2** [comment]
There is no reason for rling -s (the -d is implied) to be faster than sort -u, since sort has a small subset of the features of rling.  rling -s is slower than rling -bs for many cases, due to the overhead of computing the hashes (and memory allocation, and the like).  And sort doesn't take a list of remove files... But sure, let's try it:

`rling -s 1billion.txt /dev/null            162.44 seconds`
`rling -bs 1billion.txt /dev/null          161.91 seconds`
`sort -u 1billion.txt >/dev/null          1189.88 seconds`

So yes, rling -s and rling -bs are in fact faster than sort -u.  

With regards to the second point.

1.  It's just an example of how to use rling in a pipeline to do a useful task.
2. Lots of programs (including many of mine) have gzip support built in on read.  Not so many include xz support. Few support both.
3. "Far superior" seems somewhat... subjective.   As with all things, it depends on the usage case.
